version: 2.1

description: |
  Experimental orb for working with the Octopus CLI. This orb is provided as-is, with no support available.

  Email circleci@octopus.com if you have questions about the orb.
display:
  source_url: https://github.com/stopthatastronaut/octopus-cli-orb
  home_url: https://github.com/stopthatastronaut/octopus-cli-orb
